/*
NAME: MUZZAMIL KHAN
COURSE: MAPD713 - ENTERPRISE TECH
DESC: ASSIGNMENT 1 - WRITING ENDPOINT SERVER THAT WILL RESPONDE TO MY APP'S FRONTEND
GITHUB REPO ADD: https://github.com/KhanMuzz/MAPD713_EnterpriseTech.git
*/
